version: '3.1'

services:

  mysql:
    image: library/mysql:5.7
    command: --wait_timeout=800 --max_allowed_packet=256M --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080