#######################################################
authorize:
  path: api/v1/authorize
  controller: App\Controller\LoginController::authorize

access:
  path: api/v1/access
  controller: App\Controller\LoginController::access

artists:
  path: api/v1/artists
  controller: App\Controller\ArtistController::getArtists

init:
  path: api/v1/init
  controller: App\Controller\InitController::init
  method: [POST]